Repository MattWalterTX/Rancid-Tomatillos, pull requests merged in 2022-12, with the labels that each got.

#10 Adds files and folders for project
  src/AllMovies/AllMovies-test.js
  src/AllMovies/AllMovies.css
  src/AllMovies/AllMovies.js
  src/Info/Info-test.js
  src/Info/Info.css
  src/Info/Info.js
  src/MovieTile/MovieTile-test.js
  src/MovieTile/MovieTile.css
  src/MovieTile/MovieTile.js
  src/SingleView/SingleView-test.js
  src/SingleView/SingleView.css
  src/SingleView/SingleView.js
Labels: Setup

#12 Adds dummy data
  src/movieData.js
Labels: Setup

#13 Adds a render of one movie
  src/App.js
  src/MovieTile/MovieTile.css
  src/MovieTile/MovieTile.js
  src/movieData.js
Labels: Component

#14 Display movies
  public/index.html
  src/AllMovies/AllMovies.js
  src/App.js
  src/MovieTile/MovieTile.css
  src/MovieTile/MovieTile.js
  src/movieData.js
Labels: bug, Setup, Component, CSS

#16 All movies displayed
  src/AllMovies/AllMovies.css
  src/AllMovies/AllMovies.js
  src/App.css
  src/App.js
  src/MovieTile/MovieTile.css
  src/MovieTile/MovieTile.js
Labels: enhancement, Component, CSS

#15 Connect api
  src/App.js
  src/movieData.js
Labels: Component, API

#20 Adds error handling
  src/App.js
Labels: API, Error Handling

#26 Adds cypress tests
  cypress.config.js
  cypress/e2e/onLoad_spec.cy.js
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
  public/index.html
  public/kisspng-tomato-tomatillo-fruit-and-vegetable-wash-food-green-tomato-5b0a3fc837e275.0694252115273983442289.png
  src/AllMovies/AllMovies.css
  src/App.css
  src/App.js
  src/MovieTile/MovieTile.js
  src/SingleView/SingleView.css
Labels: CSS, testing

#27 Router
  package-lock.json
  package.json
  public/coollogo_com-283914743.png
  src/AllMovies/AllMovies.js
  src/App.js
  src/Info/Info.js
  src/MovieTile/MovieTile.js
  src/index.js
Labels: enhancement, CSS

#34 Styling update
  src/App.css
  src/Info/Info.css
  src/Info/Info.js
  src/SingleView/SingleView.css
Labels: Component, CSS

#35 Fix: allow reload of single view pages
  package-lock.json
  package.json
  src/AllMovies/AllMovies.js
  src/App.js
  src/DetailContainer/DetailContainer.js
  src/MovieTile/MovieTile.js
Labels: bug fix

#36 Testing refactor
  cypress/e2e/onLoad_spec.cy.js
  cypress/e2e/singleView_spec.cy.js
  src/App.js
Labels: Refactor, testing

#37 Adds proptypes to relevant components
  package-lock.json
  package.json
  src/AllMovies/AllMovies.js
  src/DetailContainer/DetailContainer.js
  src/Info/Info.js
  src/MovieTile/MovieTile.js
  src/SingleView/SingleView.js
Labels: enhancement, Component

#41 Adds a button to error page
  src/App.css
  src/App.js
  src/NotFound/NotFound.css
  src/NotFound/NotFound.js
  src/index.js
  src/movieData.js
Labels: Error Handling
